// Emoji helpers for the DM subsystem: Twemoji rendering, curated picker
// sets, and `:name:` shortcode lookup + autocomplete. Kept dependency-free
// so it can be unit-tested in isolation.

export const TWEMOJI_URL = 'https://cdn.jsdelivr.net/gh/jdecked/twemoji@latest/assets/72x72';

/** Matches emoji runs: pictographs (+ ZWJ sequences, variation selectors, skin tones), symbols/dingbats, keycaps, flags. */
export const EMOJI_SEGMENT_RE =
  /(?:\p{Extended_Pictographic}(?:\u200D\p{Extended_Pictographic}|\uFE0F|\u20E3|[\u{1F3FB}-\u{1F3FF}])*\uFE0F?|\p{Regional_Indicator}{2}|[\u2600-\u27BF]\uFE0F?|[\u0023-\u0039]\uFE0F?\u20E3)/gu;

const SHORTCODE_RE = /:[A-Za-z0-9_+\-]+:/g;

/**
 * Converts an emoji run to its Twemoji filename: lowercase hex codepoints
 * joined with '-', with the U+FE0F variation selector stripped (e.g.
 * 👍🏽 → `1f44d-1f3fd`, ❤️ → `2764`).
 */
export function twemojiFilename(emoji: string): string {
  return Array.from(emoji.replace(/\uFE0F/g, ''))
    .map((c) => c.codePointAt(0)!.toString(16))
    .join('-');
}

export function twemojiUrl(emoji: string): string {
  return `${TWEMOJI_URL}/${twemojiFilename(emoji)}.png`;
}

/** Splits a text run into plain-text and emoji segments (TWEMOJI-ready). */
export function splitEmojiText(text: string): Array<{ text: string; emoji: boolean }> {
  const segments: Array<{ text: string; emoji: boolean }> = [];
  let last = 0;
  for (const match of text.matchAll(EMOJI_SEGMENT_RE)) {
    const idx = match.index ?? 0;
    if (idx > last) segments.push({ text: text.slice(last, idx), emoji: false });
    segments.push({ text: match[0], emoji: true });
    last = idx + match[0].length;
  }
  if (last < text.length) segments.push({ text: text.slice(last), emoji: false });
  return segments;
}

/** True when the string is a single complete emoji (used to validate reactions). */
export function isSingleEmoji(value: string): boolean {
  if (!value || value.length > 16) return false;
  const matched = value.match(EMOJI_SEGMENT_RE);
  return matched !== null && matched.length === 1 && matched[0] === value;
}

export interface EmojiCategory {
  id: string;
  labelKey: string;
  items: string[];
}

/** Builds a country-flag emoji from its ISO 3166-1 alpha-2 code (avoids hand-typed codepoint mistakes). */
function flag(cc: string): string {
  return Array.from(cc.toUpperCase())
    .map((ch) => String.fromCodePoint(0x1f1e6 + ch.charCodeAt(0) - 65))
    .join('');
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    labelKey: 'dm.emojiCatSmileys',
    items: [
      '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '😊', '😇', '🙂', '😉',
      '😍', '🥰', '😘', '😗', '😙', '😚', '😋', '😛', '😝', '😜', '🤪', '🤨',
      '🧐', '🤓', '😎', '🥳', '😏', '😒', '😞', '😔', '😟', '😕', '🙁', '😣',
      '😖', '😫', '😩', '🥺', '😢', '😭', '😤', '😠', '😡', '🤬', '🤯', '😳',
      '🥵', '🥶', '😱', '😨', '😰', '😥', '😓', '🤗', '🤔', '🤭', '🤫', '🥱',
      '😴', '😮', '😯', '😦', '😧', '😐', '😶'
    ]
  },
  {
    id: 'gestures',
    labelKey: 'dm.emojiCatGestures',
    items: [
      '👍', '🙌', '👏', '👌', '✌️', '🤞', '🤟', '🤘', '🤙', '👋', '✋', '🤚',
      '🖖', '☝️', '👆', '👇', '👉', '👈', '🙏', '🤝', '✊', '👊', '🫶', '💪',
      '🤳', '🦾', '👀', '👅', '🧠', '💯', '✔️', '💥', '🔥', '✨', '🎉', '🏆'
    ]
  },
  {
    id: 'hearts',
    labelKey: 'dm.emojiCatHearts',
    items: [
      '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '❤️‍🔥',
      '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '♥️', '💋', '💌', '😻'
    ]
  },
  {
    id: 'symbols',
    labelKey: 'dm.emojiCatSymbols',
    items: [
      '✅', '❌', '❎', '❗', '❕', '⚠️', '🚫', '🔞', '💢', '🔒', '🔓', '🔑',
      '🔔', '🔕', '📌', '📍', '📎', '✂️', '💬', '💭', '👾', '🛸', '🌍', '🌈',
      '☀️', '🌙', '⚡', '❄️', '☄️', '💧', '🌊', '🍕', '🍔', '🧋', '☕', '🍵',
      '🎧', '🎮', '🎤', '🚀', '🎁', '🐱', '🐶', '🦊'
    ]
  },
  {
    id: 'animals',
    labelKey: 'dm.emojiCatAnimals',
    items: [
      '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯', '🦁', '🐮',
      '🐷', '🐸', '🐵', '🐔', '🐧', '🐦', '🐤', '🦆', '🦅', '🦉', '🦇', '🐺',
      '🐴', '🦄', '🐝', '🦋', '🐌', '🐞', '🐢', '🐍', '🦎', '🐙', '🦑', '🐠',
      '🐟', '🐡', '🐬', '🐳', '🐋', '🦈', '🐊', '🐪', '🦒', '🦘', '🐕', '🐈',
      '🦃', '🦚', '🦜', '🦢', '🐇', '🦔', '🐾', '🐉', '🌵', '🌲', '🌳', '🌴',
      '🌱', '🌿', '🍀', '🌾', '💐', '🌷', '🌹', '🌺', '🌸', '🌼', '🌻', '🌞',
      '🌝', '🌚', '🌕', '🌙', '🌎', '🌍', '🌏', '⭐', '🌟', '💫', '⚡', '🔥',
      '🌈', '☀️', '☁️', '❄️', '⛄', '💨', '💧', '💦', '☔', '🌊', '🌋', '🗻'
    ]
  },
  {
    id: 'food',
    labelKey: 'dm.emojiCatFood',
    items: [
      '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', '🍒', '🍑', '🥭',
      '🍍', '🥥', '🥝', '🍅', '🥑', '🥦', '🥬', '🥒', '🌽', '🫑', '🥕', '🥔',
      '🍠', '🥐', '🥯', '🍞', '🥖', '🥨', '🧀', '🥚', '🍳', '🧈', '🥞', '🧇',
      '🥓', '🥩', '🍗', '🍖', '🌭', '🍔', '🍟', '🍕', '🥪', '🥙', '🌮', '🌯',
      '🥗', '🍿', '🍚', '🍜', '🍝', '🍣', '🍤', '🥟', '🍱', '🍛', '🍲', '🍥',
      '🍦', '🍨', '🍧', '🍰', '🎂', '🧁', '🥧', '🍫', '🍬', '🍭', '🍮', '🍯',
      '☕', '🍵', '🧃', '🥤', '🧋', '🍶', '🍺', '🍻', '🥂', '🍷', '🥃', '🍾'
    ]
  },
  {
    id: 'activities',
    labelKey: 'dm.emojiCatActivities',
    items: [
      '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🏓', '🏸',
      '🏒', '🏑', '🏏', '⛳', '🏹', '🎣', '🥊', '🥋', '🎽', '⛸️', '🥌', '🎿',
      '⛷️', '🏂', '🏋️', '🤼', '🤸', '🤺', '🏌️', '🏇', '🧘', '🏄', '🏊', '🚣',
      '🧗', '🚵', '🚴', '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🏟️', '🎮', '🕹️',
      '🎲', '♟️', '🎯', '🎳', '🎪', '🎭', '🎨', '🎬', '🎤', '🎧', '🎼', '🎹',
      '🥁', '🎷', '🎺', '🎸', '🎻', '🎥', '📷', '🎟️', '🎫', '🎁', '🎈', '🎀',
      '🎊', '🎉', '🎎', '🎐', '🎃'
    ]
  },
  {
    id: 'travel',
    labelKey: 'dm.emojiCatTravel',
    items: [
      '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚',
      '🚛', '🚜', '🛴', '🚲', '🛵', '🏍️', '🛺', '🚨', '🚔', '🚍', '🚘', '🚖',
      '🚡', '🚠', '🚟', '🚃', '🚋', '🚞', '🚝', '🚄', '🚅', '🚈', '🚂', '🚆',
      '🚇', '🚊', '🚉', '✈️', '🛫', '🛬', '🛩️', '💺', '🛰️', '🚀', '🛸', '🚁',
      '🛶', '⛵', '🚤', '🛥️', '🛳️', '⛴️', '🚢', '⚓', '⛽', '🚧', '🚦', '🚥',
      '🚏', '🗺️', '🗽', '🗼', '🏰', '🏯', '🎡', '🎢', '🎠', '⛲', '⛱️', '🏖️',
      '🏝️', '🏜️', '🏕️', '🏠', '🏡', '🏘️', '🏢', '🏭', '🏬', '🏣', '🏦', '🏨',
      '🏪', '🏫', '🏩', '💒', '🏛️', '⛪', '🕌', '🕍', '🛕', '⛩️'
    ]
  },
  {
    id: 'objects',
    labelKey: 'dm.emojiCatObjects',
    items: [
      '⌚', '📱', '📲', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '💾', '💿', '📀', '📞',
      '☎️', '📟', '📠', '📺', '📻', '🎙️', '🎚️', '⏱️', '⏲️', '⏰', '🕰️', '⌛',
      '⏳', '📡', '🔋', '🔌', '💡', '🔦', '🕯️', '🧯', '💸', '💵', '💰', '💳',
      '💎', '⚖️', '🧰', '🔧', '🔨', '⚒️', '🛠️', '🗡️', '⚔️', '🛡️', '💣', '🧨',
      '🗑️', '🛎️', '🔑', '🗝️', '🔭', '🔬', '💉', '💊', '🩺', '🚪', '🛏️', '🛋️',
      '🪑', '🚽', '🚿', '🛁', '🧻', '🧹', '🧺', '🧽', '🧴', '⚗️', '🧪', '🧬',
      '🎒', '📚', '📕', '📗', '📘', '📙', '📔', '📓', '📃', '📜', '📄', '📰',
      '📑', '🔖', '🏷️', '📊', '📈', '📉', '🗒️', '🗓️', '📆', '📅', '📁', '📂',
      '🗂️', '📎', '🖇️', '📐', '📏', '📌', '📍', '✂️', '🖊️', '🖋️', '✒️', '🖌️',
      '🖍️', '📝', '✏️', '🔍', '🔎', '🔏', '🔐', '🔒', '🔓'
    ]
  },
  {
    id: 'flags',
    labelKey: 'dm.emojiCatFlags',
    items: [
      '🏁', '🚩', '🎌', '🏴', '🏳️', '🏳️\u200D🌈', '🏴\u200D☠️',
      flag('us'), flag('gb'), flag('ca'), flag('au'), flag('nz'), flag('jp'),
      flag('kr'), flag('cn'), flag('de'), flag('fr'), flag('es'), flag('it'),
      flag('pt'), flag('br'), flag('mx'), flag('in'), flag('id'), flag('th'),
      flag('vn'), flag('ph'), flag('tr'), flag('sa'), flag('il'), flag('ru'),
      flag('ua'), flag('nl'), flag('be'), flag('ch'), flag('at'), flag('se'),
      flag('no'), flag('fi'), flag('dk'), flag('pl'), flag('gr'), flag('ie')
    ]
  },
  {
    id: 'custom',
    labelKey: 'dm.emojiCatCustom',
    items: [
      '✨', '⭐', '🌟', '💫', '🌙', '☀', '🔥', '❄', '🌈', '🌊', '🍀', '🌸',
      '💮', '🎀', '🏆', '🥇', '🎯', '💎', '👑', '💰', '🔮', '🗝️', '🛡️', '⚔️',
      '📖', '⏳', '⌛', '🕯️', '🪄', '🧊', '🌹', '🦋', '🕊️', '✨', '🎈', '🎊'
    ]
  }
];

/** Convenience quick-set shown in the message reaction "+" picker. */
export const QUICK_REACTIONS = ['👍', '❤️', '😂', '🔥', '😮', '😢', '🎉', '👏'];

// ---------------------------------------------------------------------------
// `:name:` shortcode map (github-style lowercase names with underscores).
// ---------------------------------------------------------------------------

export const EMOJI_BY_NAME: Record<string, string> = {
  // Smileys
  grinning: '😀',
  smiley: '😃',
  smile: '😄',
  grin: '😁',
  laughing: '😆',
  satisfied: '😆',
  sweat_smile: '😅',
  rofl: '🤣',
  joy: '😂',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  wink: '😉',
  blush: '😊',
  innocent: '😇',
  smiling_face_with_three_hearts: '🥰',
  heart_eyes: '😍',
  star_struck: '🤩',
  kissing_heart: '😘',
  kissing: '😗',
  relaxed: '☺️',
  kissing_closed_eyes: '😚',
  kissing_smiling_eyes: '😙',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  zany_face: '🤪',
  stuck_out_tongue_closed_eyes: '😝',
  money_mouth_face: '🤑',
  nerd_face: '🤓',
  sunglasses: '😎',
  partying_face: '🥳',
  smirk: '😏',
  unamused: '😒',
  disappointed: '😞',
  pensive: '😔',
  worried: '😟',
  confused: '😕',
  slight_frown: '🙁',
  frowning_face: '☹️',
  persevere: '😣',
  confounded: '😖',
  tired_face: '😫',
  weary: '😩',
  pleading_face: '🥺',
  cry: '😢',
  sob: '😭',
  angry: '😠',
  rage: '😡',
  pouting_face: '😡',
  symbols_over_head: '🤬',
  exploding_head: '🤯',
  flushed: '😳',
  hot_face: '🥵',
  cold_face: '🥶',
  scream: '😱',
  fearful: '😨',
  cold_sweat: '😰',
  sweat: '😥',
  sweat_drops: '💦',
  hugging_face: '🤗',
  thinking: '🤔',
  hand_over_mouth: '🤭',
  shushing_face: '🤫',
  yawning_face: '🥱',
  sleeping: '😴',
  open_mouth: '😮',
  hushed: '😯',
  frowning: '😦',
  anguished: '😧',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  smiley_cat: '😺',
  smile_cat: '😸',
  joy_cat: '😹',
  heart_eyes_cat: '😻',
  smirk_cat: '😼',
  kissing_cat: '😽',
  scream_cat: '🙀',
  crying_cat_face: '😿',
  pouting_cat: '😾',
  // Gestures / body
  thumbsup: '👍',
  '+1': '👍',
  thumbsdown: '👎',
  '-1': '👎',
  raised_hands: '🙌',
  clap: '👏',
  ok_hand: '👌',
  victory: '✌️',
  crossed_fingers: '🤞',
  love_you_gesture: '🤟',
  sign_of_the_horns: '🤘',
  call_me_hand: '🤙',
  wave: '👋',
  hand: '✋',
  raised_back_of_hand: '🤚',
  vulcan_salute: '🖖',
  point_up_2: '👆',
  point_down: '👇',
  point_right: '👉',
  point_left: '👈',
  point_up: '☝️',
  pray: '🙏',
  handshake: '🤝',
  fist: '✊',
  punch: '👊',
  muscle: '💪',
  selfie: '🤳',
  mechanical_arm: '🦾',
  eyes: '👀',
  tongue: '👅',
  brain: '🧠',
  hundred: '💯',
  heavy_check_mark: '✔️',
  boom: '💥',
  fire: '🔥',
  sparkles: '✨',
  party_popper: '🎉',
  trophy: '🏆',
  // Hearts
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  broken_heart: '💔',
  heart_exclamation: '❣️',
  heart_on_fire: '❤️‍🔥',
  two_hearts: '💕',
  revolving_hearts: '💞',
  heartbeat: '💓',
  heartpulse: '💗',
  sparkling_heart: '💖',
  cupid: '💘',
  gift_heart: '💝',
  heart_decoration: '💟',
  heart_arrow: '♥️',
  kiss: '💋',
  love_letter: '💌',
  // Nature / animals
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  hamster: '🐹',
  rabbit: '🐰',
  fox_face: '🦊',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  baby_chick: '🐤',
  duck: '🦆',
  eagle: '🦅',
  owl: '🦉',
  bat: '🦇',
  wolf: '🐺',
  horse: '🐴',
  unicorn: '🦄',
  bee: '🐝',
  butterfly: '🦋',
  snail: '🐌',
  beetle: '🐞',
  turtle: '🐢',
  snake: '🐍',
  lizard: '🦎',
  octopus: '🐙',
  squid: '🦑',
  fish: '🐟',
  tropical_fish: '🐠',
  blowfish: '🐡',
  dolphin: '🐬',
  whale: '🐳',
  shark: '🦈',
  crocodile: '🐊',
  camel: '🐪',
  giraffe: '🦒',
  kangaroo: '🦘',
  cactus: '🌵',
  evergreen_tree: '🌲',
  deciduous_tree: '🌳',
  palm_tree: '🌴',
  seedling: '🌱',
  herb: '🌿',
  four_leaf_clover: '🍀',
  sheaf_of_rice: '🌾',
  bouquet: '💐',
  tulip: '🌷',
  rose: '🌹',
  hibiscus: '🌺',
  cherry_blossom: '🌸',
  blossom: '🌼',
  sunflower: '🌻',
  sun_with_face: '🌞',
  full_moon_with_face: '🌝',
  new_moon_with_face: '🌚',
  full_moon: '🌕',
  crescent_moon: '🌙',
  earth_americas: '🌎',
  earth_africa: '🌍',
  earth_asia: '🌏',
  star: '⭐',
  star2: '🌟',
  dizzy: '💫',
  zap: '⚡',
  fire_nature: '🔥',
  rainbow: '🌈',
  sunny: '☀️',
  cloud: '☁️',
  snowflake: '❄️',
  snowman: '⛄',
  dash: '💨',
  droplet: '💧',
  sweat_drops_sym: '💦',
  umbrella: '☔',
  ocean: '🌊',
  volcano: '🌋',
  mountain_fuji: '🗻',
  // Food
  apple: '🍎',
  pear: '🍐',
  tangerine: '🍊',
  lemon: '🍋',
  banana: '🍌',
  watermelon: '🍉',
  grapes: '🍇',
  strawberry: '🍓',
  blueberries: '🫐',
  cherries: '🍒',
  peach: '🍑',
  mango: '🥭',
  pineapple: '🍍',
  coconut: '🥥',
  kiwi_fruit: '🥝',
  tomato: '🍅',
  avocado: '🥑',
  broccoli: '🥦',
  leafy_green: '🥬',
  cucumber: '🥒',
  corn: '🌽',
  bell_pepper: '🫑',
  carrot: '🥕',
  potato: '🥔',
  croissant: '🥐',
  bagel: '🥯',
  bread: '🍞',
  baguette_bread: '🥖',
  pretzel: '🥨',
  cheese: '🧀',
  egg: '🥚',
  fried_egg: '🍳',
  butter: '🧈',
  pancakes: '🥞',
  waffle: '🧇',
  bacon: '🥓',
  meat_on_bone: '🍖',
  poultry_leg: '🍗',
  hotdog: '🌭',
  hamburger: '🍔',
  fries: '🍟',
  pizza: '🍕',
  sandwich: '🥪',
  stuffed_flatbread: '🥙',
  taco: '🌮',
  burrito: '🌯',
  salad: '🥗',
  popcorn: '🍿',
  rice: '🍚',
  ramen: '🍜',
  spaghetti: '🍝',
  sushi: '🍣',
  shrimp: '🍤',
  dumpling: '🥟',
  bento: '🍱',
  curry: '🍛',
  stew: '🍲',
  icecream: '🍦',
  ice_cream: '🍨',
  shaved_ice: '🍧',
  cake: '🍰',
  birthday: '🎂',
  cupcake: '🧁',
  pie: '🥧',
  chocolate_bar: '🍫',
  candy: '🍬',
  lollipop: '🍭',
  pudding: '🍮',
  honey_pot: '🍯',
  coffee: '☕',
  tea: '🍵',
  juice_box: '🧃',
  cup_with_straw: '🥤',
  bubble_tea: '🧋',
  sake: '🍶',
  beer: '🍺',
  beers: '🍻',
  clinking_glasses: '🥂',
  wine_glass: '🍷',
  tumbler_glass: '🥃',
  cocktail: '🍸',
  tropical_drink: '🍹',
  bottle_with_popping_cork: '🍾',
  // Activities
  soccer: '⚽',
  basketball: '🏀',
  football: '🏈',
  baseball: '⚾',
  softball: '🥎',
  tennis: '🎾',
  volleyball: '🏐',
  rugby_football: '🏉',
  flying_disc: '🥏',
  pool_8_ball: '🎱',
  ping_pong: '🏓',
  badminton: '🏸',
  ice_hockey: '🏒',
  field_hockey: '🏑',
  cricket_game: '🏏',
  flag_in_hole: '⛳',
  bow_and_arrow: '🏹',
  fishing_pole_and_fish: '🎣',
  boxing_glove: '🥊',
  martial_arts_uniform: '🥋',
  running_shirt_with_sash: '🎽',
  ice_skate: '⛸️',
  curling_stone: '🥌',
  ski: '🎿',
  skier: '⛷️',
  snowboarder: '🏂',
  weight_lifter: '🏋️',
  wrestlers: '🤼',
  person_doing_cartwheel: '🤸',
  fencer: '🤺',
  golfer: '🏌️',
  horse_racing: '🏇',
  person_in_lotus_position: '🧘',
  surfer: '🏄',
  swimmer: '🏊',
  person_rowing_boat: '🚣',
  person_climbing: '🧗',
  mountain_bicyclist: '🚵',
  bicyclist: '🚴',
  first_place_medal: '🥇',
  second_place_medal: '🥈',
  third_place_medal: '🥉',
  sports_medal: '🏅',
  military_medal: '🎖️',
  stadium: '🏟️',
  video_game: '🎮',
  joystick: '🕹️',
  game_die: '🎲',
  chess_pawn: '♟️',
  dart: '🎯',
  bowling: '🎳',
  circus_tent: '🎪',
  performing_arts: '🎭',
  art: '🎨',
  clapper: '🎬',
  microphone: '🎤',
  headphones: '🎧',
  musical_score: '🎼',
  musical_keyboard: '🎹',
  drum: '🥁',
  saxophone: '🎷',
  trumpet: '🎺',
  guitar: '🎸',
  violin: '🎻',
  movie_camera: '🎥',
  camera: '📷',
  ticket: '🎟️',
  gift: '🎁',
  balloon: '🎈',
  ribbon: '🎀',
  confetti_ball: '🎊',
  tada: '🎉',
  crown: '👑',
  jack_o_lantern: '🎃',
  // Travel
  red_car: '🚗',
  taxi: '🚕',
  blue_car: '🚙',
  bus: '🚌',
  trolleybus: '🚎',
  racing_car: '🏎️',
  police_car: '🚓',
  ambulance: '🚑',
  fire_engine: '🚒',
  minibus: '🚐',
  pickup_truck: '🛻',
  truck: '🚚',
  articulated_lorry: '🚛',
  tractor: '🚜',
  kick_scooter: '🛴',
  bicycle: '🚲',
  motor_scooter: '🛵',
  motorcycle: '🏍️',
  auto_rickshaw: '🛺',
  car: '🚗',
  police_car_light: '🚨',
  police_car_siren: '🚔',
  oncoming_bus: '🚍',
  oncoming_automobile: '🚘',
  oncoming_taxi: '🚖',
  aerial_tramway: '🚡',
  mountain_cableway: '🚠',
  suspension_railway: '🚟',
  railway_car: '🚃',
  tram: '🚋',
  monorail: '🚝',
  high_speed_train: '🚄',
  bullet_train: '🚅',
  light_rail: '🚈',
  locomotive: '🚂',
  train: '🚆',
  metro: '🚇',
  tram_car: '🚊',
  station: '🚉',
  airplane: '✈️',
  airplane_departure: '🛫',
  airplane_arrival: '🛬',
  small_airplane: '🛩️',
  seat: '💺',
  satellite: '🛰️',
  rocket: '🚀',
  flying_saucer: '🛸',
  helicopter: '🚁',
  canoe: '🛶',
  sailboat: '⛵',
  speedboat: '🚤',
  motor_boat: '🛥️',
  cruise_ship: '🛳️',
  ferry: '⛴️',
  ship: '🚢',
  anchor: '⚓',
  fuelpump: '⛽',
  construction: '🚧',
  vertical_traffic_light: '🚦',
  traffic_light: '🚥',
  busstop: '🚏',
  world_map: '🗺️',
  statue_of_liberty: '🗽',
  tokyo_tower: '🗼',
  castle: '🏰',
  japanese_castle: '🏯',
  ferris_wheel: '🎡',
  roller_coaster: '🎢',
  carousel_horse: '🎠',
  fountain: '⛲',
  beach_umbrella: '⛱️',
  beach_with_umbrella: '🏖️',
  desert_island: '🏝️',
  desert: '🏜️',
  camping: '🏕️',
  house: '🏠',
  house_with_garden: '🏡',
  houses: '🏘️',
  office: '🏢',
  factory: '🏭',
  department_store: '🏬',
  post_office: '🏣',
  european_post_office: '🏤',
  hospital: '🏥',
  bank: '🏦',
  hotel: '🏨',
  convenience_store: '🏪',
  school: '🏫',
  love_hotel: '🏩',
  wedding: '💒',
  classical_building: '🏛️',
  church: '⛪',
  mosque: '🕌',
  synagogue: '🕍',
  hindu_temple: '🛕',
  shinto_shrine: '⛩️',
  // Objects
  watch: '⌚',
  iphone: '📱',
  mobile_phone_with_arrow: '📲',
  computer: '💻',
  keyboard: '⌨️',
  desktop_computer: '🖥️',
  printer: '🖨️',
  computer_mouse: '🖱️',
  floppy_disk: '💾',
  cd: '💿',
  dvd: '📀',
  telephone: '📞',
  telephone_receiver: '☎️',
  pager: '📟',
  fax: '📠',
  tv: '📺',
  radio: '📻',
  studio_microphone: '🎙️',
  level_slider: '🎚️',
  stopwatch: '⏱️',
  timer_clock: '⏲️',
  alarm_clock: '⏰',
  mantelpiece_clock: '🕰️',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  satellite_antenna: '📡',
  battery: '🔋',
  electric_plug: '🔌',
  bulb: '💡',
  flashlight: '🔦',
  candle: '🕯️',
  fire_extinguisher: '🧯',
  money_with_wings: '💸',
  dollar: '💵',
  moneybag: '💰',
  credit_card: '💳',
  gem: '💎',
  scales: '⚖️',
  toolbox: '🧰',
  wrench: '🔧',
  hammer: '🔨',
  hammer_and_wrench: '🛠️',
  dagger: '🗡️',
  crossed_swords: '⚔️',
  shield: '🛡️',
  bomb: '💣',
  firecracker: '🧨',
  wastebasket: '🗑️',
  bellhop_bell: '🛎️',
  key: '🔑',
  old_key: '🗝️',
  telescope: '🔭',
  microscope: '🔬',
  syringe: '💉',
  pill: '💊',
  stethoscope: '🩺',
  door: '🚪',
  bed: '🛏️',
  couch_and_lamp: '🛋️',
  chair: '🪑',
  toilet: '🚽',
  shower: '🚿',
  bathtub: '🛁',
  roll_of_paper: '🧻',
  broom: '🧹',
  basket: '🧺',
  sponge: '🧽',
  lotion_bottle: '🧴',
  alembic: '⚗️',
  test_tube: '🧪',
  dna: '🧬',
  school_satchel: '🎒',
  books: '📚',
  closed_book: '📕',
  green_book: '📗',
  blue_book: '📘',
  orange_book: '📙',
  notebook: '📓',
  page_with_curl: '📃',
  scroll: '📜',
  page_facing_up: '📄',
  newspaper: '📰',
  bookmark: '🔖',
  label: '🏷️',
  bar_chart: '📊',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  memo: '📝',
  pencil2: '✏️',
  briefcase: '💼',
  folder: '📁',
  open_file_folder: '📂',
  card_index_dividers: '🗂️',
  paperclip: '📎',
  paperclips: '🖇️',
  straight_ruler: '📏',
  triangular_ruler: '📐',
  pushpin: '📌',
  round_pushpin: '📍',
  scissors: '✂️',
  pen: '🖊️',
  fountain_pen: '🖋️',
  black_nib: '✒️',
  paintbrush: '🖌️',
  crayon: '🖍️',
  calendar: '📅',
  search: '🔍',
  lock: '🔒',
  unlock: '🔓',
  // Symbols (often used)
  white_check_mark: '✅',
  x: '❌',
  negative_squared_cross_mark: '❎',
  exclamation: '❗',
  grey_exclamation: '❕',
  warning: '⚠️',
  no_entry_sign: '🚫',
  underage: '🔞',
  anger: '💢',
  bell: '🔔',
  no_bell: '🔕',
  speech_balloon: '💬',
  thought_balloon: '💭',
  space_invader: '👾',
  alien: '🛸',
  gift_symbols: '🎁',
  // Flags
  checkered_flag: '🏁',
  triangular_flag_on_post: '🚩',
  crossed_flags: '🎌',
  black_flag: '🏴',
  white_flag: '🏳️',
  rainbow_flag: '🏳️\u200D🌈',
  pirate_flag: '🏴\u200D☠️',
  flag_us: flag('us'),
  us: flag('us'),
  flag_gb: flag('gb'),
  uk: flag('gb'),
  flag_ca: flag('ca'),
  ca: flag('ca'),
  flag_au: flag('au'),
  au: flag('au'),
  flag_jp: flag('jp'),
  jp: flag('jp'),
  flag_kr: flag('kr'),
  kr: flag('kr'),
  flag_cn: flag('cn'),
  cn: flag('cn'),
  flag_de: flag('de'),
  de: flag('de'),
  flag_fr: flag('fr'),
  fr: flag('fr'),
  flag_es: flag('es'),
  es: flag('es'),
  flag_it: flag('it'),
  it: flag('it'),
  flag_br: flag('br'),
  br: flag('br'),
  flag_mx: flag('mx'),
  mx: flag('mx'),
  flag_in: flag('in'),
  flag_th: flag('th'),
  th: flag('th'),
  flag_vn: flag('vn'),
  flag_tr: flag('tr'),
  flag_il: flag('il'),
  flag_ru: flag('ru'),
  flag_ua: flag('ua'),
  flag_nl: flag('nl'),
  flag_ch: flag('ch'),
  flag_se: flag('se'),
  flag_no: flag('no'),
  flag_dk: flag('dk'),
  flag_pl: flag('pl')
};

/** Show a small tasteful default set when the user has typed a lone `:`. */
export const POPULAR_AUTOCOMPLETE_NAMES = [
  'sunglasses',
  'smile',
  'joy',
  'heart',
  'fire',
  'sparkles',
  'thumbsup',
  'clap',
  'smirk',
  'wave',
  'rocket',
  'party_popper',
  'crown',
  'game_die',
  'pizza',
  'taco',
  'cat',
  'dog',
  'muscle',
  'pray'
];

export interface EmojiAutocompleteEntry {
  name: string;
  emoji: string;
}

/**
 * Returns `{name, emoji}` suggestions for a shortcode prefix (without the
 * colons). An empty prefix yields a curated popular set. Matches are ranked
 * with prefix hits before substring hits and returned up to `limit`.
 */
export function findEmojiAutocompletions(prefix: string, limit = 10): EmojiAutocompleteEntry[] {
  const q = prefix.trim().toLowerCase();
  if (!q) {
    return POPULAR_AUTOCOMPLETE_NAMES.map((name) => ({ name, emoji: EMOJI_BY_NAME[name] }))
      .filter((e) => !!e.emoji)
      .slice(0, limit);
  }
  const names = Object.keys(EMOJI_BY_NAME);
  const starts: string[] = [];
  const contains: string[] = [];
  for (const name of names) {
    const lower = name.toLowerCase();
    if (lower.startsWith(q)) starts.push(name);
    else if (lower.includes(q)) contains.push(name);
  }
  starts.sort();
  contains.sort();
  return [...starts, ...contains].slice(0, limit).map((name) => ({ name, emoji: EMOJI_BY_NAME[name] }));
}

/** Replaces every known `:name:` shortcode in a string with its emoji (unknown names are left untouched). */
export function replaceEmojiShortcodes(text: string): string {
  return text.replace(SHORTCODE_RE, (m) => EMOJI_BY_NAME[m.slice(1, -1).toLowerCase()] ?? m);
}